version: 2.1
orbs:
   node: circleci/node@4.2
jobs:
  build:
    docker:
      - image: cimg/node
    steps:
      - checkout
      - run: echo "this is the build job"
  deploy:
    executor: node/default
    steps:
      - checkout
      - run: echo "this is the deploy job"
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: main