version: 2.1
orbs:
   node: circleci/node@4.2
jobs:
  build:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: echo "this is the build job"
  
workflows:
  build-and-deploy:
    jobs:
      