version: '2.1'
orbs:
   node: circleci/node@4.2
jobs:
  deploy:
    executor: node/default
    steps:
      - checkout
// handles cache automatically
      - node/install-packages:
          override-ci-command: npm i --production
      - run: npm install
workflows:
  test-and-deploy:
    jobs:
// Should work out of the box, cache is automatic
      - node/test
// deploy runs after test and only on the main branch
      - deploy:
          requires:
            - node/test
          filters:
            branches:
              only: main