version: 2.1
orbs:
   node: circleci/node@4.2
jobs:
  deploy:
    executor: node/default
    steps:
      - checkout
      - run: npm install
workflows:
  test-and-deploy:
    jobs:
      - deploy:
          requires:
            - node/test
          filters:
            branches:
              only: main