version: 2.1
orbs:
   node: circleci/node@4.2
jobs:
  build:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run: echo "build job"
  test:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run: echo "test job"
  deploy:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run: echo "deploy job"
workflows:
  build_and_test_and_deploy:
    jobs:
      - build
      - test
      - deploy
      





      